#!/usr/bin/env python3
"""Parse 7000-word Level 2–6 lists → 11505-7000-core.js"""
import re
from pathlib import Path

DIR = Path(__file__).resolve().parent
LEVEL_FILES = [
    (2, ["＠7000單合併版_Level2_二級（1053字）.txt", "@7000單合併版_Level2_二級（1053字）.txt"]),
    (3, ["＠7000單合併版_Level3_三級（1053字）.txt", "@7000單合併版_Level3_三級（1053字）.txt"]),
    (4, ["＠7000單合併版_Level4_四級（1056字）.txt", "@7000單合併版_Level4_四級（1056字）.txt"]),
    (5, ["＠7000單合併版_Level5_五級（1187字）.txt", "@7000單合併版_Level5_五級（1187字）.txt"]),
    (6, ["＠7000單合併版_Level6_六級（1292字）.txt", "@7000單合併版_Level6_六級（1292字）.txt"]),
]
WORD_RE = re.compile(r"[A-Za-z][A-Za-z'-]*")


def parse_file(path: Path) -> set[str]:
    words = set()
    text = path.read_text(encoding="utf-8", errors="replace")
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("=") or "Level" in line or "7000" in line[:20]:
            continue
        for m in WORD_RE.finditer(line):
            w = m.group(0).lower()
            if len(w) > 1 or w == "a":
                words.add(w)
    return words


def main():
    levels: dict[str, int] = {}
    for lv, names in LEVEL_FILES:
        path = None
        for name in names:
            p = DIR / name
            if p.is_file():
                path = p
                break
        if not path:
            print(f"WARN: missing level {lv} file")
            continue
        for w in parse_file(path):
            levels[w] = max(levels.get(w, 0), lv)

    out = DIR / "11505-7000-core.js"
    lines = [
        "/* AUTO-GENERATED by _build_7000_core.py — 7000單 Level 2–6 */",
        "window.CORE7000_LEVELS = {",
    ]
    for w in sorted(levels):
        lines.append(f'  "{w}":{levels[w]},')
    lines.append("};")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"Wrote {len(levels)} words → {out}")


if __name__ == "__main__":
    main()
